CREATE DATABASE studentinfodatabase;

USE studentinfodatabase;

CREATE TABLE STUDENT(
STUDENT_ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50),
EMAIL_ID VARCHAR(200),
LOCATION VARCHAR(200),
PHONE_NUMBER INT NOT NULL,
CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_ID));

CREATE TABLE SUBJECT(
SUBJECT_ID VARCHAR(20) NOT NULL,
SUBJECT_NAME VARCHAR(50) NOT NULL,
CONSTRAINT PK_SUBJECT PRIMARY KEY(SUBJECT_ID));

CREATE TABLE GLOBAL_TEACHER(
TEACHER_ID INT NOT NULL,
TEACHER_NAME varchar(50) NOT NULL,
SUBJECT_ID_LEVEL_1 varchar(50) NOT NULL,
SUBJECT_ID_LEVEL_2 varchar(50),
SUBJECT_ID_LEVEL_3 varchar(50),
SUBJECT_ID_LEVEL_4 varchar(50),
CLASS_ID_LEVEL_1 varchar(50) NOT NULL,
CLASS_ID_LEVEL_2 varchar(50),
CLASS_ID_LEVEL_3 varchar(50),
CLASS_ID_LEVEL_4 varchar(50),
LOCATION_ID_LEVEL_1 varchar(50) NOT NULL,
LOCATION_ID_LEVEL_2 varchar(50),
LOCATION_ID_LEVEL_3 varchar(50),
LOCATION_ID_LEVEL_4 varchar(50),
CITY_ID_LEVEL_1 VARCHAR(50) NOT NULL,
CITY_ID_LEVEL_2 varchar(50),
CITY_ID_LEVEL_3 varchar(50),
CONSTRAINT PK_TEACHER PRIMARY KEY(TEACHER_ID));

CREATE TABLE CLASS(
CLASS_ID VARCHAR(20) NOT NULL,
CLASS_NAME VARCHAR(50) NOT NULL,
CONSTRAINT PK_CLASS PRIMARY KEY(CLASS_ID));

CREATE TABLE LOCATION(
LOCATION_ID VARCHAR(20) NOT null,
LOCATION_NAME VARCHAR(50) NOT NULL,
CONSTRAINT PK_LOCATION PRIMARY KEY(LOCATION_ID));

-----Need to check--------
CREATE TABLE RATING(
TEACHER_ID INT NOT null,
RATING_VALUE VARCHAR(50) NOT null,
CONSTRAINT PK_RATING PRIMARY KEY(TEACHER_ID));

CREATE TABLE CITY(
CITY_ID VARCHAR(20) NOT null,
CITY_NAME VARCHAR(50) NOT NULL,
CONSTRAINT PK_CITY PRIMARY KEY(CITY_ID));

CREATE TABLE IMAGE(
TEACHER_ID INT NOT null,
TEACHER_IMAGE BLOB,
CONSTRAINT PK_IMAGE PRIMARY KEY(TEACHER_ID));

------Global Teacher----------
CREATE TABLE GLOBAL_TEACHER(
TEACHER_ID INT NOT NULL,
TEACHER_NAME varchar(50) NOT NULL,
SUBJECT_ID_LEVEL_1 varchar(50) NOT NULL,
SUBJECT_ID_LEVEL_2 varchar(50),
SUBJECT_ID_LEVEL_3 varchar(50),
SUBJECT_ID_LEVEL_4 varchar(50),
CLASS_ID_LEVEL_1 varchar(50) NOT NULL,
CLASS_ID_LEVEL_2 varchar(50),
CLASS_ID_LEVEL_3 varchar(50),
CLASS_ID_LEVEL_4 varchar(50),
LOCATION_ID_LEVEL_1 varchar(50) NOT NULL,
LOCATION_ID_LEVEL_2 varchar(50),
LOCATION_ID_LEVEL_3 varchar(50),
LOCATION_ID_LEVEL_4 varchar(50),
CITY_ID_LEVEL_1 VARCHAR(50) NOT NULL,
CITY_ID_LEVEL_2 varchar(50),
CITY_ID_LEVEL_3 varchar(50),
CONSTRAINT PK_TEACHER PRIMARY KEY(TEACHER_ID));

------Alter command to add NOT NULL-----------
alter table GLOBAL_TEACHER modify SUBJECT_ID_LEVEL_1 varchar(50) NOT NULL;
alter table GLOBAL_TEACHER modify CLASS_ID_LEVEL_1 varchar(50) NOT NULL;
alter table GLOBAL_TEACHER modify LOCATION_ID_LEVEL_1 varchar(50) NOT NULL;
alter table GLOBAL_TEACHER modify CITY_ID_LEVEL_1 varchar(50) NOT NULL;




